RWTexture2D<float4> Source;
RWTexture2D<float4> Target;

uint BitReverse(uint x) {
    x = ((x & 0x55555555) << 1) | ((x & 0xAAAAAAAA) >> 1);
    x = ((x & 0x33333333) << 2) | ((x & 0xCCCCCCCC) >> 2);
    x = ((x & 0x0F0F0F0F) << 4) | ((x & 0xF0F0F0F0) >> 4);
    x = ((x & 0x00FF00FF) << 8) | ((x & 0xFF00FF00) >> 8);
    x = (x << 16) | (x >> 16);
    return x;
}

float2 ComplexMul(float2 z, float2 w) {
    return float2(z.x * w.x - z.y * w.y, z.x * w.y + z.y * w.x);
}

cbuffer FFT {
    uint N;
};

[numthreads(16,16,1)]
void main(int3 ThreadID: SV_DispatchThreadID) {
    int2 TexelCoord = ThreadID.xy;

    float2 Sample = Target[TexelCoord].rg;

    float2 Result = 

    Target[ThreadID.xy] = Result;
}
