RWTexture2D<float4> Target;

static const float Tau = 6.28318530718f; // 2*Pi

cbuffer FFT: register(b10) {
    uint N;
    uint Direction;
    uint Stage;
};

float2 ComplexMul(float2 z, float2 w) {
    return float2(z.x * w.x - z.y * w.y, z.x * w.y + z.y * w.x);
}

float2 GetTwiddle(uint k, uint n) {
    float Angle = Tau * k / n;
    return float2(cos(Angle), sin(Angle));
}

[numthreads(16,16,1)]
void main(int3 ThreadID: SV_DispatchThreadID) {
    uint StageSize = 1 << Stage;
    uint SubSize = StageSize << 1;
    
    // Vertical
    if (Direction) {
        uint BlockIndex = ThreadID.y / StageSize;
        uint k = ThreadID.y % StageSize;

        uint Index0 = BlockIndex * SubSize + k;
        uint Index1 = BlockIndex * SubSize + k + StageSize;
        
        float2 z0 = Target[int2(ThreadID.x, Index0)].rg;
        float2 z1 = Target[int2(ThreadID.x, Index1)].rg;
        
        float2 Twiddle = GetTwiddle(k, SubSize);
        
        Target[int2(ThreadID.x, Index0)] = float4(z0 + ComplexMul(Twiddle, z1), 0.0f, 1.0f);
        Target[int2(ThreadID.x, Index1)] = float4(z0 - ComplexMul(Twiddle, z1), 0.0f, 1.0f);
    }
    // Horizontal
    else {
        uint BlockIndex = ThreadID.x / StageSize;
        uint k = ThreadID.x % StageSize;

        uint Index0 = BlockIndex * SubSize + k;
        uint Index1 = BlockIndex * SubSize + k + StageSize;
        
        float2 z0 = Target[int2(Index0, ThreadID.y)].rg;
        float2 z1 = Target[int2(Index1, ThreadID.y)].rg;
        
        float2 Twiddle = GetTwiddle(k, SubSize);
        
        Target[int2(Index0, ThreadID.y)] = float4(z0 + ComplexMul(Twiddle, z1), 0.0f, 1.0f);
        Target[int2(Index1, ThreadID.y)] = float4(z0 - ComplexMul(Twiddle, z1), 0.0f, 1.0f);
    }
}