RWTexture2D<float4> Target;

static const float Tau = 6.28318530718f; // 2*Pi

cbuffer FFT: register(b10) {
    uint N;
    uint Direction;
    uint Stage;
};

[numthreads(16,16,1)]
void main(int3 ThreadID: SV_DispatchThreadID) {
    int2 TexCoord = ThreadID.xy;
    float2 Z = Target[TexCoord].rg;
    float Module = length(Z) / (N*N);
    float Phase = atan2(Z.y, Z.x);
    Target[TexCoord] = float4(Module*float3(1.0f, 1.0f, 1.0f), 1.0f);
}