RWTexture2D<float4> Target;

cbuffer Globals: register(b0) {
    float4x4 Projection;
    float4x4 View;
    float2 Resolution;
    float2 Mouse;
    float2 LastMouse;
    float Time;
};

cbuffer Color: register(b2) {
    float4 Color;
}

cbuffer Outline: register(b5) {
    float Width;
    int Level;
};

[numthreads(16,16,1)]
void main(int3 ThreadID: SV_DispatchThreadID) {
    int2 TexelCoord = ThreadID.xy;
    if (ThreadID.x >= Resolution.x || ThreadID.y >= Resolution.y) {
        return;
    }

	float4 Value = Target[TexelCoord];

    float4 Result = float4(0., 0., 0., 0.);
	if (Value.b > 0.) {
		float D = distance(TexelCoord, Value.rg);

		if (D >= Width) {
			Result = float4(0., 0., 0., 0.);
		}
		else {
			double Alpha = Color.a;
			if (D >= Width - 1.) {
				Alpha *= (Width - D);
			}
			Result = float4(Alpha*Color.rgb, Alpha);
		}
	}

    Target[TexelCoord] = Result;
}
