static const float A = 200.0f;
static const float Tau = 6.28318530718f; // 2*Pi
static const float g = 9.807f;           // Gravitational constant, in m/s^2

RWTexture2D<float4> Target;

cbuffer Globals: register(b0) {
    float4x4 Projection;
    float4x4 View;
    float2 Resolution;
    float2 Mouse;
    float2 LastMouse;
    float Time;
};

cbuffer Sea: register(b9) {
    float3 Dimensions;
    float2 Wind;
};

float random (float2 p) {
    return frac(sin(dot(p, float2(12.9898,78.233)))*43758.5453123);
}

float2 normal(float2 p) {
    float r = sqrt(-2.0f * log(random(p)));
    float theta = Tau*random(p + float2(0.3211f, 0.72361f));

    return float2(r*cos(theta), r*sin(theta));
}

float2 expi(float Angle) {
    return float2(cos(Angle), sin(Angle));
}

float2 ComplexMul(float2 Z, float2 W) {
    return float2(Z.x * W.x - Z.y * W.y, Z.x * W.y + Z.y * W.x);
}

float2 Conjugate(float2 Z) {
    return float2(Z.x, -Z.y);
}

float2 WaveVector(float2 Coord, float2 k) {
    float V = length(Wind); // Wind speed
    float L = V*V/g;        // Largest wave

    float k_sq = dot(k, k);

    float Value = 0.0f;
    if (k_sq != 0.0f) {
        float Cos = dot(normalize(Wind), normalize(k));
        Value = A * abs(Cos) * exp(-1.0f / (k_sq * L * L)) / k_sq;
    }

    float2 Result = Value * normal(Coord / 1024.0f);
    return isinf(Result) || isnan(Result) ? float2(0.0f, 0.0f) : Result;
}

[numthreads(16,16,1)]
void main(int3 ThreadID: SV_DispatchThreadID) {
    int2 Coord0 = ThreadID.xy;
    int2 Coord1 = 1023 - ThreadID.xy;

    float dx = 1024.0f / Dimensions.x;
    float dz = 1024.0f / Dimensions.z;

    float2 k0 = Tau * (float2(Coord0) - 512.0f) / float2(dx, dz);
    float2 k1 = Tau * (float2(Coord1) - 512.0f) / float2(dx, dz);

    float2 WaveVector0 = WaveVector(Coord0, k0);
    float2 WaveVector1 = WaveVector(Coord1, k1);

    float w = sqrt(g * length(k0));

    float2 Result0 = ComplexMul(WaveVector0, expi(Tau*w*Time)) + ComplexMul(Conjugate(WaveVector1), expi(-Tau*w*Time));
    float2 Result1 = ComplexMul(WaveVector1, expi(Tau*w*Time)) + ComplexMul(Conjugate(WaveVector0), expi(-Tau*w*Time));

    Target[Coord0] = float4(Result0, 0.0f, 1.0f);
    Target[Coord1] = float4(Result1, 0.0f, 1.0f);
}
