#ifndef GAME_ENUMS
#define GAME_ENUMS

enum debug_type {
    Debug_Type_bool,
    Debug_Type_char,
    Debug_Type_string,
    Debug_Type_int8,
    Debug_Type_int16,
    Debug_Type_int,
    Debug_Type_int32,
    Debug_Type_int64,
    Debug_Type_uint8,
    Debug_Type_uint16,
    Debug_Type_uint32,
    Debug_Type_uint64,
    Debug_Type_memory_index,
    Debug_Type_float,
    Debug_Type_double,
    Debug_Type_v2,
    Debug_Type_v3,
    Debug_Type_v4,
    Debug_Type_scale,
    Debug_Type_quaternion,
    Debug_Type_color,
    Debug_Type_collider,
    Debug_Type_memory_arena,
    Debug_Type_game_asset_type,
    Debug_Type_game_text_id,
    Debug_Type_game_heightmap_id,
    Debug_Type_game_animation_id,
    Debug_Type_game_mesh_id,
    Debug_Type_game_bitmap_id,
    Debug_Type_game_entity_type,
    Debug_Type_enemy_type,
    Debug_Type_magic_affinity,
    Debug_Type_spell_id,
    Debug_Type_weapon_type,
    Debug_Type_character_action_id,
    Debug_Type_character_class,
    Debug_Type_altered_state,
    Debug_Type_room_type,
    Debug_Type_game_state_type,
    Debug_Type_transform,
    Debug_Type_segment3,
    Debug_Type_game_animation,
    Debug_Type_game_animator,
    Debug_Type_bone,
    Debug_Type_armature,
    Debug_Type_game_entity,
    Debug_Type_stats,
    Debug_Type_enemy,
    Debug_Type_weapon,
    Debug_Type_character_action,
    Debug_Type_character,
};

bool IsEnumType(debug_type Type) { return Type > 22 && Type < 39; }

struct debug_enum_value {
    debug_type EnumType;
    const char* Identifier;
    int Value;
};

const int ENUM_VALUES_SIZE = 153;
debug_enum_value EnumValues[ENUM_VALUES_SIZE] = {
    {Debug_Type_game_asset_type, "Asset_Type_Text", 0},
    {Debug_Type_game_asset_type, "Asset_Type_Bitmap", 1},
    {Debug_Type_game_asset_type, "Asset_Type_Heightmap", 2},
    {Debug_Type_game_asset_type, "Asset_Type_Font", 3},
    {Debug_Type_game_asset_type, "Asset_Type_Sound", 4},
    {Debug_Type_game_asset_type, "Asset_Type_Video", 5},
    {Debug_Type_game_asset_type, "Asset_Type_Mesh", 6},
    {Debug_Type_game_asset_type, "Asset_Type_Animation", 7},
    {Debug_Type_game_asset_type, "game_asset_type_count", 8},
    {Debug_Type_game_text_id, "Text_Test_ID", 0},
    {Debug_Type_game_text_id, "game_text_id_count", 1},
    {Debug_Type_game_heightmap_id, "Heightmap_Spain_ID", 0},
    {Debug_Type_game_heightmap_id, "game_heightmap_id_count", 1},
    {Debug_Type_game_animation_id, "Animation_Idle_ID", 0},
    {Debug_Type_game_animation_id, "Animation_Walk_ID", 1},
    {Debug_Type_game_animation_id, "Animation_Jump_ID", 2},
    {Debug_Type_game_animation_id, "Animation_Attack_ID", 3},
    {Debug_Type_game_animation_id, "game_animation_id_count", 4},
    {Debug_Type_game_mesh_id, "Mesh_Horns_ID", 0},
    {Debug_Type_game_mesh_id, "Mesh_Dog_ID", 1},
    {Debug_Type_game_mesh_id, "Mesh_Dyno_ID", 2},
    {Debug_Type_game_mesh_id, "Mesh_Sphere_ID", 3},
    {Debug_Type_game_mesh_id, "Mesh_Body_ID", 4},
    {Debug_Type_game_mesh_id, "Mesh_Shield_ID", 5},
    {Debug_Type_game_mesh_id, "Mesh_Sword_ID", 6},
    {Debug_Type_game_mesh_id, "Mesh_Staff_ID", 7},
    {Debug_Type_game_mesh_id, "Mesh_Selector_ID", 8},
    {Debug_Type_game_mesh_id, "game_mesh_id_count", 9},
    {Debug_Type_game_bitmap_id, "Bitmap_Background_ID", 0},
    {Debug_Type_game_bitmap_id, "Bitmap_Button_ID", 1},
    {Debug_Type_game_bitmap_id, "Bitmap_Empty_ID", 2},
    {Debug_Type_game_bitmap_id, "Bitmap_Enemy_ID", 3},
    {Debug_Type_game_bitmap_id, "Bitmap_Player_ID", 4},
    {Debug_Type_game_bitmap_id, "Bitmap_Anvil_ID", 5},
    {Debug_Type_game_bitmap_id, "Bitmap_Combat_ID", 6},
    {Debug_Type_game_bitmap_id, "Bitmap_Fire_ID", 7},
    {Debug_Type_game_bitmap_id, "Bitmap_Coin_ID", 8},
    {Debug_Type_game_bitmap_id, "Bitmap_Quest_ID", 9},
    {Debug_Type_game_bitmap_id, "Bitmap_Wizard_ID", 10},
    {Debug_Type_game_bitmap_id, "Bitmap_Miniboss_ID", 11},
    {Debug_Type_game_bitmap_id, "Bitmap_Boss_ID", 12},
    {Debug_Type_game_bitmap_id, "game_bitmap_id_count", 13},
    {Debug_Type_game_entity_type, "Entity_Type_Character", 0},
    {Debug_Type_game_entity_type, "Entity_Type_Enemy", 1},
    {Debug_Type_game_entity_type, "Entity_Type_Camera", 2},
    {Debug_Type_game_entity_type, "Entity_Type_Prop", 3},
    {Debug_Type_game_entity_type, "Entity_Type_Weapon", 4},
    {Debug_Type_game_entity_type, "game_entity_type_count", 5},
    {Debug_Type_enemy_type, "Enemy_Type_Horns", 0},
    {Debug_Type_enemy_type, "Enemy_Type_Dog", 1},
    {Debug_Type_enemy_type, "Enemy_Type_Miniboss_Dyno", 2},
    {Debug_Type_enemy_type, "Enemy_Type_Boss_Test", 3},
    {Debug_Type_enemy_type, "enemy_type_count", 4},
    {Debug_Type_magic_affinity, "Magic_Affinity_None", 0},
    {Debug_Type_magic_affinity, "Magic_Affinity_Fire", 1},
    {Debug_Type_magic_affinity, "Magic_Affinity_Earth", 2},
    {Debug_Type_magic_affinity, "Magic_Affinity_Water", 3},
    {Debug_Type_magic_affinity, "Magic_Affinity_Ice", 4},
    {Debug_Type_magic_affinity, "Magic_Affinity_Air", 5},
    {Debug_Type_magic_affinity, "Magic_Affinity_Death", 6},
    {Debug_Type_magic_affinity, "Magic_Affinity_Life", 7},
    {Debug_Type_magic_affinity, "Magic_Affinity_Time", 8},
    {Debug_Type_magic_affinity, "magic_affinity_count", 9},
    {Debug_Type_spell_id, "Spell_Empty", 0},
    {Debug_Type_spell_id, "Spell_Fireball", 1},
    {Debug_Type_spell_id, "Spell_Burn", 2},
    {Debug_Type_spell_id, "Spell_Incinerate", 3},
    {Debug_Type_spell_id, "Spell_Explosion", 4},
    {Debug_Type_spell_id, "Spell_Rock_Throw", 5},
    {Debug_Type_spell_id, "Spell_Spikes", 6},
    {Debug_Type_spell_id, "Spell_Rock_Armor", 7},
    {Debug_Type_spell_id, "Spell_Diamond_Armor", 8},
    {Debug_Type_spell_id, "Spell_Sand_Storm", 9},
    {Debug_Type_spell_id, "Spell_Sand_Burst", 10},
    {Debug_Type_spell_id, "Spell_Mud_Pack", 11},
    {Debug_Type_spell_id, "Spell_Earthquake", 12},
    {Debug_Type_spell_id, "Spell_Drench", 13},
    {Debug_Type_spell_id, "Spell_Wave", 14},
    {Debug_Type_spell_id, "Spell_Drown", 15},
    {Debug_Type_spell_id, "Spell_Cascade", 16},
    {Debug_Type_spell_id, "Spell_Wash", 17},
    {Debug_Type_spell_id, "Spell_Hydrate", 18},
    {Debug_Type_spell_id, "Spell_Icicle", 19},
    {Debug_Type_spell_id, "Spell_Blizzard", 20},
    {Debug_Type_spell_id, "Spell_Freeze", 21},
    {Debug_Type_spell_id, "Spell_Ice_Armor", 22},
    {Debug_Type_spell_id, "Spell_Snow_Golem", 23},
    {Debug_Type_spell_id, "Spell_Absolute_Zero", 24},
    {Debug_Type_spell_id, "Spell_Wind", 25},
    {Debug_Type_spell_id, "Spell_Gust", 26},
    {Debug_Type_spell_id, "Spell_Fly", 27},
    {Debug_Type_spell_id, "Spell_Air_Shield", 28},
    {Debug_Type_spell_id, "Spell_Tornado", 29},
    {Debug_Type_spell_id, "Spell_Hurricane", 30},
    {Debug_Type_spell_id, "Spell_Poison", 31},
    {Debug_Type_spell_id, "Spell_Rot", 32},
    {Debug_Type_spell_id, "Spell_Bleed", 33},
    {Debug_Type_spell_id, "Spell_Kill", 34},
    {Debug_Type_spell_id, "Spell_Zombie", 35},
    {Debug_Type_spell_id, "Spell_Multikill", 36},
    {Debug_Type_spell_id, "Spell_Cure", 37},
    {Debug_Type_spell_id, "Spell_Heal", 38},
    {Debug_Type_spell_id, "Spell_Regeneration", 39},
    {Debug_Type_spell_id, "Spell_Multicure", 40},
    {Debug_Type_spell_id, "Spell_Multiheal", 41},
    {Debug_Type_spell_id, "Spell_Resurrect", 42},
    {Debug_Type_spell_id, "Spell_Slow", 43},
    {Debug_Type_spell_id, "Spell_Accelerate", 44},
    {Debug_Type_spell_id, "Spell_Tempo", 45},
    {Debug_Type_spell_id, "Spell_Stop", 46},
    {Debug_Type_spell_id, "Spell_Rewind", 47},
    {Debug_Type_spell_id, "spell_id_count", 48},
    {Debug_Type_weapon_type, "Weapon_Sword", 0},
    {Debug_Type_weapon_type, "Weapon_Shield", 1},
    {Debug_Type_weapon_type, "Weapon_Staff", 2},
    {Debug_Type_weapon_type, "weapon_type_count", 3},
    {Debug_Type_character_action_id, "Character_Action_Idle_ID", 0},
    {Debug_Type_character_action_id, "Character_Action_Walk_ID", 1},
    {Debug_Type_character_action_id, "Character_Action_Jump_ID", 2},
    {Debug_Type_character_action_id, "Character_Action_Attack_ID", 3},
    {Debug_Type_character_action_id, "character_action_id_count", 4},
    {Debug_Type_character_class, "Class_Knight", 0},
    {Debug_Type_character_class, "Class_Rogue", 1},
    {Debug_Type_character_class, "Class_Hunter", 2},
    {Debug_Type_character_class, "Class_Wizard", 3},
    {Debug_Type_character_class, "character_class_count", 4},
    {Debug_Type_altered_state, "altered_state_none", 0},
    {Debug_Type_altered_state, "altered_state_burned", 1},
    {Debug_Type_altered_state, "altered_state_wet", 2},
    {Debug_Type_altered_state, "altered_state_frozen", 3},
    {Debug_Type_altered_state, "altered_state_drowning", 4},
    {Debug_Type_altered_state, "altered_state_poisoned", 5},
    {Debug_Type_altered_state, "altered_state_rotting", 6},
    {Debug_Type_altered_state, "altered_state_bleeding", 7},
    {Debug_Type_altered_state, "altered_state_dead", 8},
    {Debug_Type_altered_state, "altered_state_regenerating", 9},
    {Debug_Type_altered_state, "altered_state_count", 10},
    {Debug_Type_room_type, "Room_Type_Combat", 0},
    {Debug_Type_room_type, "Room_Type_Camp", 1},
    {Debug_Type_room_type, "Room_Type_Merchant", 2},
    {Debug_Type_room_type, "Room_Type_Blacksmith", 3},
    {Debug_Type_room_type, "Room_Type_Wizard", 4},
    {Debug_Type_room_type, "Room_Type_Quest", 5},
    {Debug_Type_room_type, "Room_Type_Miniboss", 6},
    {Debug_Type_room_type, "Room_Type_Boss", 7},
    {Debug_Type_room_type, "room_type_count", 8},
    {Debug_Type_game_state_type, "Game_State_Main_Menu", 0},
    {Debug_Type_game_state_type, "Game_State_Combat", 1},
    {Debug_Type_game_state_type, "Game_State_Camp", 2},
    {Debug_Type_game_state_type, "Game_State_Trade", 3},
    {Debug_Type_game_state_type, "Game_State_Map", 4},
    {Debug_Type_game_state_type, "Game_State_Credits", 5},
    {Debug_Type_game_state_type, "game_state_type_count", 6},
};

#endif